name: Business Card PR Validation

on:
  push:
    branches:
      - BusinessCards

jobs:
  validate-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Krok 3: Sprawdzenie, czy nowe pliki i edycje są w katalogu `businessCardImages` oraz mają prawidłowy format.
      - name: Validate file locations and formats
        run: |
          ALLOWED_FORMATS=("jpg" "jpeg" "png" "gif" "webp" "bmp")
          for file in $(git diff --name-only HEAD^ HEAD); do
            if [[ "$file" == *"businessCardImages"* ]]; then
              extension="${file##*.}"
              if [[ ! " ${ALLOWED_FORMATS[@]} " =~ " ${extension,,} " ]]; then
                echo "Błąd: ${file} ma niedozwolony format. Dopuszczalne: ${ALLOWED_FORMATS[*]}"
                exit 1
              fi
            elif [[ "$file" != "laravel/resources/settings/businessCardSettings.php" ]]; then
              echo "Błąd: Zmiany poza katalogiem 'businessCardImages' są niedozwolone."
              exit 1
            fi
          done

      # Krok 4: Walidacja składni PHP w pliku `businessCardSettings.php`
      - name: Validate PHP syntax in businessCardSettings.php
        run: |
          php -l laravel/resources/settings/businessCardSettings.php
          
      # Krok 5: Walidacja struktury pliku `businessCardSettings.php`
      - name: Validate businessCardSettings.php structure
        run: |
          php -r '
          $file = "laravel/resources/settings/businessCardSettings.php";
          $data = include $file;
          
          if (!isset($data["elements"])) {
              echo "Błąd: Brak sekcji elements.";
              exit(1);
          }
          
          foreach ($data["elements"] as $key => $element) {
              if (!preg_match("/^ele[0-9]+$/", $key)) {
                  echo "Błąd: Element klucza \"$key\" musi być w formacie ele1, ele2, ...";
                  exit(1);
              }
              $fields = ["name", "pictureName", "tel", "email", "web", "description"];
              foreach ($fields as $field) {
                  if (!array_key_exists($field, $element)) {
                      echo "Błąd: Element \"$key\" musi zawierać pole \"$field\".";
                      exit(1);
                  }
              }
              if (strlen($element["name"]) > 25) {
                  echo "Błąd: Pole 'name' w elemencie \"$key\" przekracza 25 znaków.";
                  exit(1);
              }
              if (strlen($element["description"]) > 100) {
                  echo "Błąd: Pole 'description' w elemencie \"$key\" przekracza 100 znaków.";
                  exit(1);
              }
          }
          '

      # Krok 6: Tworzenie pull requesta, jeśli walidacje przejdą pomyślnie
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: master
          title: "Automated PR from BusinessCards branch"
          body: "Zmiany automatycznie zatwierdzone na podstawie walidacji."
