name: Auto Merge Pull Request and Deploy

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Permissions
        run: |
          echo "Testowanie uprawnień tokena dla dostępu API"
          curl -H "Authorization: token ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/

      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}
          script: |
            if (context.payload.pull_request.base.ref === 'master') {
              const { owner, repo } = context.repo;
              const pull_number = context.payload.pull_request.number;

              try {
                await github.rest.pulls.merge({
                  owner,
                  repo,
                  pull_number,
                  merge_method: 'merge'
                });
                console.log(`Pomyślnie połączono PR #${pull_number}`);
              } catch (error) {
                console.error('Błąd podczas łączenia PR:', error);
                core.setFailed(error.message);
              }
            } else {
              console.log('Nie łączę PR, ponieważ nie jest skierowany do mastera.');
            }

  deploy:
    needs: auto_merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalacja klucza SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key

      - name: Dodanie known hosts
        run: |
          echo "${{ secrets.SSH_HOST }} ssh-ed25519 SHA256:Qgvy72Ewn07hlW7c7TTvU/+Fft89WE7K+yVYDWA4b8M" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test połączenia SSH
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "Połączenie SSH udane"'

      - name: Wdrożenie na serwer
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            cd ./domains/kurierportal.cfolks.pl/public_html/courier_portal/laravel/ && \
            git checkout master && \
            git pull origin master
          '

      - name: Czyszczenie
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key
          eval $(ssh-agent -k)