name: Auto Merge Pull Request
on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Permissions
        run: |
          echo "Token permissions:"
          curl -H "Authorization: token ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/
        
      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}
          script: |
            if (context.payload.pull_request.base.ref === 'master') {
              const { owner, repo } = context.repo;
              const pull_number = context.payload.pull_request.number;

              try {
                await github.rest.pulls.merge({
                  owner,
                  repo,
                  pull_number,
                  merge_method: 'merge'
                });
                console.log(`Successfully merged PR #${pull_number}`);
              } catch (error) {
                console.error('Error merging PR:', error);
                core.setFailed(error.message);
              }
            } else {
              console.log('Not merging PR because it is not targeting master.');
            }

      - name: Debug API Response
        if: always()
        run: |
          echo "Testing API access to specific PR:"
          curl -H "Authorization: token ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
