name: Automatically Create Pull Request and Redirect

on:
  push:
    branches:
      - BusinessCards

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: master
          branch: BusinessCards
          title: 'Automatyczny pull request z brancha BusinessCards'
          body: 'Automatycznie wygenerowany pull request z brancha BusinessCards'

      - name: Redirect to Pull Requests
        if: steps.create-pr.outputs.pull-request-url != ''
        run: |
          echo "Pull Request URL: ${{ steps.create-pr.outputs.pull-request-url }}"
          echo "::notice::Przekierowanie do Pull Requesta: ${{ steps.create-pr.outputs.pull-request-url }}"