name: Create or Update Pull Request

on:
  push:
    branches:
      - BusinessCards

jobs:
  create_or_update_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pobierz pełną historię commitów

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Check for existing pull request
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }} # Użyj swojego tokena
        run: |
          pr_number=$(gh pr list --base master --head BusinessCards --json number --jq '.[0].number')
          echo "PR Number: $pr_number"
          echo "pr_number=$pr_number" >> $GITHUB_ENV

      - name: Create or update Pull Request
        run: |
          if [ -z "$pr_number" ]; then
            gh pr create --base master --head BusinessCards --title "Automated PR from BusinessCards" --body "This is an automated pull request from the BusinessCards branch."
          else
            gh pr edit "$pr_number" --title "Updated PR from BusinessCards" --body "This PR was updated automatically from the BusinessCards branch."
          fi
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }} # Użyj swojego tokena
