name: Create Pull Request
on:
  push:
    branches:
      - BusinessCards
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automatyczny pull request z BusinessCards'
          body: 'Ten pull request został automatycznie utworzony na podstawie zmian wprowadzonych w branchu BusinessCards.'
          head: BusinessCards
          base: master
      
      - name: Get Pull Request URL
        id: get_pr_url
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:BusinessCards`,
              state: 'open'
            });
            return pullRequests.data.length > 0 ? pullRequests.data[0].html_url : null;
      
      - name: Output Pull Request Link
        run: echo "Pull Request URL: ${{ steps.get_pr_url.outputs.result }}"