name: Create Pull Request

on:
  push:
    branches:
      - BusinessCards

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Klonuje repozytorium do środowiska roboczego

      - name: List branches
        run: git branch -a 