name: Create Pull Request

on:
  push:
    branches:
      - BusinessCards

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pobierz pełną historię commitów

      - name: Fetch all branches
        run: git fetch --all

      - name: Debug info
        run: |
          echo "Current branch:"
          git rev-parse --abbrev-ref HEAD
          echo "Last commit on master:"
          git rev-parse origin/master
          echo "Last commit on BusinessCards:"
          git rev-parse origin/BusinessCards
          echo "Status of BusinessCards branch:"
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}
          title: Automated PR from BusinessCards
          body: This is an automated pull request from the BusinessCards branch.
          base: master
          branch: BusinessCards  # Upewnij się, że używasz 'branch' zamiast 'head'
          draft: false


