name: Create Pull Request

on:
  push:
    branches:
      - BusinessCards

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pobierz pełną historię commitów

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Create Pull Request
        run: |
          gh pr create --base master --head BusinessCards --title "Automated PR from BusinessCards" --body "This is an automated pull request from the BusinessCards branch."
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN_COURIER_PORTAL }}
