name: Create Pull Request

on:
  push:
    branches:
      - BusinessCards

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automated PR from BusinessCards'
          body: 'This is an automated pull request from the BusinessCards branch.'
          base: master
          head: BusinessCards
          draft: false

      - name: Print PR Information
        env:
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
          PR_URL: ${{ steps.create_pr.outputs.pull-request-url }}
        run: |
          echo "Pull Request Number: $PR_NUMBER"
          echo "Pull Request URL: $PR_URL"