name: Create Pull Request
on:
  push:
    branches:
      - BusinessCards
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automatyczny pull request z BusinessCards'
          body: 'Ten pull request został automatycznie utworzony na podstawie zmian wprowadzonych w branchu BusinessCards.'
          head: BusinessCards
          base: master
      
      - name: Print PR Information
        env:
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
          PR_URL: ${{ steps.create_pr.outputs.pull-request-url }}
        run: |
          echo "Pull Request Number: $PR_NUMBER"
          echo "Pull Request URL: $PR_URL"