name: Check Business Cards

on:
  push:
    branches:
      - BusinessCards

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate images and settings
        run: |
          # Sprawdź, czy w katalogu z obrazkami są tylko dozwolone formaty
          IMAGE_DIR="laravel/public/images/businessCardImages"
          ALLOWED_EXTENSIONS="jpg,jpeg,png,gif,webp"
          for file in "$IMAGE_DIR"/*; do
            EXT="${file##*.}"
            if [[ ! ",$ALLOWED_EXTENSIONS," =~ ",$EXT," ]]; then
              echo "Error: Invalid image format for file: $file. Allowed formats are: $ALLOWED_EXTENSIONS."
              exit 1
            fi
          done

          # Sprawdź plik settings/businessCardSettings.php
          SETTINGS_FILE="laravel/resources/settings/businessCardSettings.php"
          if ! php -l "$SETTINGS_FILE"; then
            echo "Error: Syntax error in $SETTINGS_FILE."
            exit 1
          fi

          # Sprawdź struktury w elements
          ELEMENTS=$(php -r "require '$SETTINGS_FILE'; echo json_encode($settings['elements']);")
          echo "$ELEMENTS" | jq -e 'to_entries | .[] | 
            select(.value | has("name") and has("pictureName") and has("tel") and has("email") and has("web") and has("description")) |
            if (.value.name | length > 25) then "Error: Name exceeds 25 characters." else empty end |
            if (.value.description | length > 100) then "Error: Description exceeds 100 characters." else empty end
          ' > errors.log

          if [ -s errors.log ]; then
            cat errors.log
            exit 1
          fi
