name: Create Pull Request

on:
  push:
    branches:
      - BusinessCards
      
permissions:
  contents: write # Dodaje uprawnienia zapisu dla tokena

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Aktualizacja do nowszej wersji checkout
        
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5 # Aktualizacja do najnowszej wersji create-pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Automated PR from BusinessCards'
          body: 'This is an automated pull request from the BusinessCards branch.'
          base: master
          head: BusinessCards
          draft: false
          branch: temp-branch # Utworzenie tymczasowej gałęzi na potrzeby PR