name: Business Card Validation

on:
  push:
    branches:
      - BusinessCards
  pull_request:
    branches:
      - master

jobs:
  validate-business-cards:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Validate Image Files
      run: |
        ALLOWED_EXTENSIONS=("jpg" "jpeg" "png" "webp" "gif" "bmp" "tiff" "svg")
        IMAGES_DIR="laravel/public/images/businessCardImages"
        
        for file in "$IMAGES_DIR"/*; do
          if [ -f "$file" ]; then
            ext=$(echo "${file##*.}" | tr '[:upper:]' '[:lower:]')
            valid=0
            for allowed in "${ALLOWED_EXTENSIONS[@]}"; do
              if [ "$ext" == "$allowed" ]; then
                valid=1
                break
              fi
            done
            
            if [ $valid -eq 0 ]; then
              echo "Invalid file extension: $file"
              exit 1
            fi
          fi
        done

    - name: Validate Business Card Settings
      run: |
        PHP_FILE="laravel/resources/settings/businessCardSettings.php"
        
        # Syntax check
        php -l "$PHP_FILE"
        
        # Custom validation script
        php << 'EOF'
        <?php
        $settings = require '$PHP_FILE';
        
        // Validate settings structure
        if (!isset($settings['settings']) || !isset($settings['elements'])) {
            echo "Invalid settings structure\n";
            exit(1);
        }
        
        // Validate each element
        foreach ($settings['elements'] as $key => $element) {
            // Check if required keys exist
            $requiredKeys = ['name', 'pictureName', 'tel', 'email', 'web', 'description'];
            foreach ($requiredKeys as $requiredKey) {
                if (!array_key_exists($requiredKey, $element)) {
                    echo "Missing key $requiredKey in $key\n";
                    exit(1);
                }
            }
            
            // Validate name length
            if (strlen($element['name']) > 25) {
                echo "Name in $key exceeds 25 characters\n";
                exit(1);
            }
            
            // Validate description length
            if (strlen($element['description']) > 100) {
                echo "Description in $key exceeds 100 characters\n";
                exit(1);
            }
            
            // Validate image exists
            $imagePath = "laravel/public/images/businessCardImages/{$element['pictureName']}";
            if (!file_exists($imagePath)) {
                echo "Image {$element['pictureName']} not found for $key\n";
                exit(1);
            }
        }
        EOF

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: BusinessCards
        base: master
        title: Automatic Pull Request from BusinessCards
        body: Automated pull request after validation checks